language: node_js
node_js:
  - "lts/*"
script:
  - npm install -g eslint
  - eslint Command.js
  - npm install -g documentation
  - documentation build command.js --project-name "command.js" -f html -o docs -c documentation.yml
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: docs
  on:
    branch: master