language: node_js
node_js:
  - "lts/*"
script:
  - npm run eslint
  - npm run generate-docs
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: docs
  on:
    branch: master